export const REICON_PICKER_ICON_NAMES = [
  "Activity2", "AlertTriangle", "Archive", "Bell", "BookOpen", "Bookmark",
  "Box", "Building", "Calendar", "Camera", "ChartLine", "Check",
  "CheckCircle", "ChevronDown", "ChevronLeft", "ChevronRight", "ChevronUp", "Clipboard",
  "Cloud", "Code", "Code2", "Command", "Copy", "Cpu",
  "Database", "Document2", "DocumentCode2", "DocumentText2", "Download", "Edit2",
  "Eye", "EyeOff", "File", "FileText", "FileUp", "Folder",
  "FolderOpen", "FolderFiles", "Gauge3", "Gear", "Globe", "Globe2",
  "Grid", "HardDrive", "HelpCircle", "Home", "Image", "ImagePlus",
  "ImageUp", "InfoCircle", "Keyboard", "Key", "Laptop", "Layers",
  "Link", "LinkBroken", "List", "Loader", "Lock", "LockKeyhole",
  "LockOpen", "MagicWand", "Maximize", "Menu", "Microchip", "Minimize",
  "Monitor", "Mouse", "Nodes", "Package", "Palette", "Paintbrush",
  "PasswordCheck2", "Pin", "PinOff", "Play", "Plus", "Printer",
  "Refresh", "Route", "Router", "Save22", "Scan2", "Scroll2",
  "Search", "SearchZoomIn2", "SearchZoomOut2", "Server", "Settings", "Settings2",
  "Shield", "ShieldCheck", "Sliders", "Sidebar", "SidebarLeft2", "SidebarRight2", "TerminalCircle",
  "TerminalSquare", "Trash2", "Unlock", "Upload", "Usb", "User",
  "Users", "Video", "Volume", "Warehouse", "Wifi", "Window",
  "X", "Alert", "AlertCircle", "AlertCircle2", "AlertSquare", "AlertTriangle2",
  "BellAlert", "BellOff", "BellOff2", "BellRing", "Help", "HelpSquare",
  "InfoCircle3", "Information2", "InfoSquare", "Notification", "Notification12", "Notification3",
  "Add2", "AddCircle2", "Additem2", "AddressBook", "AddressCard", "AddSquare2",
  "ArrowRotate", "ArrowsRotate", "Check3", "CheckList", "Checklist2", "ChecklistAlt",
  "CheckListSquare", "CheckRead", "CheckSquare", "Clipboard3", "ClipboardAdd", "ClipboardCheck",
  "ClipboardClose2", "ClipboardExport2", "ClipboardHeart", "ClipboardImport2", "ClipboardList", "ClipboardRemove",
  "ClipboardSlash", "ClipboardText", "ClipboardText3", "ClipboardTick2", "CloseCircle2", "CloseSquare2",
  "Closet", "Closet2", "Copy3", "Copyright", "Copyright3", "CopySuccess2",
  "Download2", "Download3", "DownloadSquare", "DownloadSquare2", "Edit22", "Minus",
  "Minus3", "MinusCircle", "MinusCirlce2", "MinusSquare", "MinusSquare3", "Pen",
  "Pen2", "Pen3", "PenAdd12", "PenAdd2", "AngleDown2", "AngleDownCircle",
  "AngleDownSquare", "AngleLeft2", "AngleLeftCircle", "AngleLeftSquare", "AngleRight2", "AngleRightCircle",
  "AngleRightSquare", "AnglesLeft", "AnglesLeft2", "AnglesRight", "AnglesRight2", "AngleUp2",
  "AngleUpCircle", "AngleUpSquare", "Arrow2", "Arrow22", "Arrow32", "ArrowBottom2",
  "ArrowCircleDown2", "ArrowCircleLeft2", "ArrowCircleRight2", "ArrowCircleUp2", "ArrowDoorIn", "ArrowDoorOut3",
  "ArrowDottedRotateAnticlockwise", "ArrowDown", "ArrowDown12", "ArrowDown2", "ArrowDown22", "ArrowDown3",
  "ArrowDown5", "ArrowDownCircle", "ArrowDownLeft2", "ArrowDownLeftCircle", "ArrowDownLeftSquare", "ArrowDownRight2",
  "ArrowDownRightCircle", "ArrowDownRightSquare", "ArrowDownSquare", "ArrowLeft", "ArrowLeft12", "ArrowLeft2",
  "ArrowLeft22", "Archive12", "Archive2", "Archive22", "Archive4", "ArchiveAdd2",
  "ArchiveBook2", "ArchiveBox", "ArchiveCheck", "ArchiveDown", "ArchiveDown2", "ArchiveMinus2",
  "ArchiveSlash2", "ArchiveTick2", "ArchiveUp", "ArchiveUp2", "Book", "Book12",
  "Book2", "Book3", "Book4", "Book6", "BookBookmark", "BookBookmark2",
  "Bookmark2", "Bookmark22", "Bookmark3", "Bookmark5", "BookmarkAdd", "BookmarkCheck",
  "BookmarkCircle", "BookmarkMinus", "BookmarkOpen", "Bookmarks", "BookmarkSlash", "BookmarkSquare",
  "BookmarkSquare2", "BookmarkX", "BookSaved2", "BookSquare2", "Document12", "DocumentCloud2",
  "DocumentCode22", "DocumentCopy2", "DocumentDownload2", "DocumentFavorite2", "DocumentFilter2", "DocumentForward2",
  "DocumentLike2", "DocumentNormal2", "DocumentPrevious2", "DocumentSketch2", "DocumentText12", "Bluetooth",
  "Bluetooth22", "Bluetooth3", "BluetoothCircle", "BluetoothCircle3", "BluetoothRectangle2", "BluetoothSquare",
  "BluetoothWave", "BrowserTerminal", "Cloud3", "CloudAdd2", "CloudBolt", "CloudBolt2",
  "CloudChange2", "CloudCheck", "CloudConnect", "CloudConnection2", "CloudCross2", "CloudDown2",
  "CloudDownload", "CloudDrizzle2", "CloudDrop", "CloudDrops", "CloudFile", "CloudFog2",
  "CloudLightning2", "CloudMinus", "CloudMinus3", "CloudNotif2", "CloudPlus", "CloudPlus3",
  "CloudRain", "CloudRemove2", "Clouds", "CloudSnow", "CloudSnow2", "CloudSnow4",
  "CloudStorage", "CloudStorm", "CloudSun", "CloudSun2", "CloudSunny2", "CloudUp2",
  "CloudUpload", "CloudX", "Code12", "Code4", "CodeCircle", "CodeCircle3",
  "CodeFile", "CodeScan", "CodeSquare", "Command3", "CommandSquare2", "Cpu3",
  "CpuBolt", "CpuCharge2", "CpuSetting2", "Keyboard3", "KeyboardOpen2", "Fingerprint",
  "Key2", "Key3", "Key5", "KeySquare", "KeySquare2", "KeySquare3",
  "KeySquare4", "KeySquare5", "KeySquare6", "KeySquare8", "Lock12", "Lock2",
  "Lock4", "LockCircle2", "LockKeyhole2", "LockKeyholeOpen", "LockKeyholeOpen2", "LockOpen2",
  "LockPassword", "LockPasswordOpen", "LockSlash2", "Password", "Password2", "Password3",
  "ExitFullscreen", "ExitFullscreenCircle", "ExitFullscreenSquare", "Fullscreen", "FullscreenCircle", "FullscreenSquare",
  "Grid12", "Grid22", "Grid32", "Grid42", "Grid52", "Grid62",
  "Grid72", "Grid82", "Grid92", "GridCirclePlus", "GridEdit2", "GridEraser2",
  "GridLock2", "List3", "ListArrowDown", "ListArrowDown2", "ListArrowUp", "ListArrowUp2",
  "ListCheck", "ListCheck2", "ListCheck3", "ListDown", "ListDown2", "ListHeart",
  "ListHeart2", "ListSquare", "ListUp", "ListUp2", "ListX", "ListX2",
  "Maximize12", "Maximize212", "Maximize22", "Maximize3", "Maximize32", "Maximize42",
  "MaximizeCircle2", "MaximizeSquare", "MaximizeSquare2", "Camera2", "Camera3", "Camera4",
  "CameraAdd", "CameraAdd2", "CameraAlt", "CameraOff", "CameraRecord", "CameraRotate",
  "CameraSlash2", "CameraSquare", "Gallery", "Gallery2", "Gallery3", "Gallery5",
  "GalleryAdd", "GalleryAdd3", "GalleryCheck", "GalleryCircle", "GalleryDownload", "GalleryEdit",
  "GalleryEdit3", "GalleryExport2", "GalleryFavorite2", "GalleryImport2", "GalleryRemove", "GalleryRemove3",
  "GallerySend", "GallerySlash2", "GalleryStar", "GalleryTick2", "GalleryWide", "Image3",
  "ImageCheck", "ImageDepth", "ImageDown", "ImageMinus", "ImageMountain", "Images2",
  "ImageSparkle", "Battery", "Battery3full2", "BatteryCharge", "BatteryCharge2", "BatteryCharging2",
  "BatteryDisable2", "BatteryEmpty12", "BatteryEmpty2", "BatteryFull", "BatteryFull2", "BatteryFull4",
  "BatteryHalf", "BatteryHalf2", "BatteryHigh", "BatteryLow"
] as const;

export const LUCIDE_FALLBACK_PICKER_ICON_NAMES = [
  "Bot", "Braces", "Brain", "Cable", "Circle", "CircleDashed",
  "CircleDot", "Columns2", "Container", "ExternalLink", "Factory", "FileType",
  "FolderInput", "GitCommit", "GitFork", "GripVertical", "MemoryStick",
  "Rows3", "Scaling", "Shell", "ShelvingUnit", "SplitSquareHorizontal",
  "Square", "Webhook", "Workflow", "WrapText", "Wrench"
] as const;

export const LEGACY_LUCIDE_ICON_NAMES = [
  "Hash", "Network", "Terminal", "Server", "Building2", "ShelvingUnit",
  "Cpu", "Activity", "Bolt", "Sun", "Bell", "Bot",
  "Wrench", "Folder", "Clock", "Doc", "Cloud", "Calendar",
  "Database", "Globe", "Lock", "Key", "Mail", "Mic",
  "Monitor", "Music", "Package", "Phone", "Pin", "Power",
  "Printer", "Radio", "Search", "Settings", "Shield", "ShoppingCart",
  "Star", "Tag", "Tool", "Trash", "Truck", "User",
  "Users", "Video", "Volume", "Watch", "Wifi", "Wind",
  "Zap", "Layers", "List", "Grid", "Archive", "BadgeCheck",
  "BookOpen", "Bookmark", "Brain", "Briefcase", "Bug", "ChartBar",
  "ChartLine", "CheckCircle", "ChevronRight", "CircleHelp", "Clipboard", "ClipboardCheck",
  "ClipboardList", "Code", "Code2", "Cog", "Command", "Compass",
  "Container", "Copy", "Download", "ExternalLink", "Eye", "File",
  "FileCode", "FileJson", "FileTerminal", "FileText", "Fingerprint", "Flag",
  "Gauge", "GitBranch", "GitCommit", "GitFork", "Github", "Hammer",
  "HardDrive", "HeartPulse", "Home", "Inbox", "Keyboard", "Laptop",
  "Link", "ListChecks", "LogIn", "LogOut", "Map", "MessageSquare",
  "MousePointer2", "PackageCheck", "PanelTop", "Play", "Plus", "Rocket",
  "Route", "Save", "Send", "Shell", "SlidersHorizontal", "Sparkles",
  "SquareTerminal", "Upload", "Usb", "Waypoints", "Webhook", "Workflow",
  "XCircle", "FolderOpen", "KeyRound", "Box", "Boxes", "Braces",
  "Factory", "Warehouse", "Landmark"
] as const;

export const ICON_PICKER_NAMES = [
  ...REICON_PICKER_ICON_NAMES,
  ...LUCIDE_FALLBACK_PICKER_ICON_NAMES,
] as const;

export const VALID_ICON_NAMES = [
  ...ICON_PICKER_NAMES,
  ...LEGACY_LUCIDE_ICON_NAMES,
] as const;
