import type { QuickCommand } from "../../../../types";

export type QuickCommandLibraryEntry = Omit<QuickCommand, "id" | "label"> & {
  libraryId: string;
  sectionKey: string;
  subsectionKey: string;
  labelKey: string;
  descriptionKey: string;
};

export const QUICK_COMMAND_LIBRARY: QuickCommandLibraryEntry[] = [
  {
    libraryId: "ai-claude-start",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.claude",
    labelKey: "terminal.quickCommandLibrary.entries.aiClaudeStart.label",
    command: "claude",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiClaudeStart.description",
    iconName: "Bot",
    accentName: "purple",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "ai-claude-bypass",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.claude",
    labelKey: "terminal.quickCommandLibrary.entries.aiClaudeBypass.label",
    command: "claude --dangerously-skip-permissions",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiClaudeBypass.description",
    iconName: "Shield",
    accentName: "red",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "ai-claude-install",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.claude",
    labelKey: "terminal.quickCommandLibrary.entries.aiClaudeInstall.label",
    command: "npm install -g @anthropic-ai/claude-code",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiClaudeInstall.description",
    iconName: "Package",
    accentName: "purple",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "ai-codex-start",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.codex",
    labelKey: "terminal.quickCommandLibrary.entries.aiCodexStart.label",
    command: "codex",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiCodexStart.description",
    iconName: "Terminal",
    accentName: "green",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "ai-codex-install",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.codex",
    labelKey: "terminal.quickCommandLibrary.entries.aiCodexInstall.label",
    command: "npm i -g @openai/codex",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiCodexInstall.description",
    iconName: "Package",
    accentName: "green",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "ai-openclaw-install",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.openclaw",
    labelKey: "terminal.quickCommandLibrary.entries.aiOpenclawInstall.label",
    command: "curl -fsSL https://openclaw.ai/install.sh | bash",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiOpenclawInstall.description",
    iconName: "Cloud",
    accentName: "orange",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "ai-openclaw-onboard",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.openclaw",
    labelKey: "terminal.quickCommandLibrary.entries.aiOpenclawOnboard.label",
    command: "openclaw onboard --install-daemon",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiOpenclawOnboard.description",
    iconName: "Wrench",
    accentName: "orange",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "ai-hermes-install",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.hermesAgents",
    labelKey: "terminal.quickCommandLibrary.entries.aiHermesInstall.label",
    command: "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiHermesInstall.description",
    iconName: "Bot",
    accentName: "cyan",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "ai-hermes-setup",
    sectionKey: "terminal.quickCommandLibrary.sections.aiAgents",
    subsectionKey: "terminal.quickCommandLibrary.subsections.hermesAgents",
    labelKey: "terminal.quickCommandLibrary.entries.aiHermesSetup.label",
    command: "hermes setup",
    descriptionKey: "terminal.quickCommandLibrary.entries.aiHermesSetup.description",
    iconName: "Settings",
    accentName: "cyan",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "sys-node-install",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.general",
    labelKey: "terminal.quickCommandLibrary.entries.sysNodeInstall.label",
    command: "nvm install --lts && nvm use --lts",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysNodeInstall.description",
    iconName: "Package",
    accentName: "green",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "sys-disk-usage",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.general",
    labelKey: "terminal.quickCommandLibrary.entries.sysDiskUsage.label",
    command: "df -h",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysDiskUsage.description",
    iconName: "Database",
    accentName: "slate",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "sys-service-status",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.general",
    labelKey: "terminal.quickCommandLibrary.entries.sysServiceStatus.label",
    command: "systemctl status ",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysServiceStatus.description",
    iconName: "Activity",
    accentName: "blue",
    sendEnter: false,
    confirm: false,
  },
  {
    libraryId: "sys-docker-install",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.docker",
    labelKey: "terminal.quickCommandLibrary.entries.sysDockerInstall.label",
    command: "curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysDockerInstall.description",
    iconName: "Package",
    accentName: "blue",
    sendEnter: true,
    confirm: true,
  },
  {
    libraryId: "sys-docker-admin",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.docker",
    labelKey: "terminal.quickCommandLibrary.entries.sysDockerAdmin.label",
    command: "docker ps -a && docker images && docker volume ls",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysDockerAdmin.description",
    iconName: "Grid",
    accentName: "sky",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "sys-docker-logs",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.docker",
    labelKey: "terminal.quickCommandLibrary.entries.sysDockerLogs.label",
    command: "docker logs -f ",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysDockerLogs.description",
    iconName: "List",
    accentName: "sky",
    sendEnter: false,
    confirm: false,
  },
  {
    libraryId: "sys-k8s-pods",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.k8s",
    labelKey: "terminal.quickCommandLibrary.entries.sysK8sPods.label",
    command: "kubectl get pods -A -o wide",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysK8sPods.description",
    iconName: "Layers",
    accentName: "indigo",
    sendEnter: true,
    confirm: false,
  },
  {
    libraryId: "sys-k8s-logs",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.k8s",
    labelKey: "terminal.quickCommandLibrary.entries.sysK8sLogs.label",
    command: "kubectl logs -f ",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysK8sLogs.description",
    iconName: "List",
    accentName: "indigo",
    sendEnter: false,
    confirm: false,
  },
  {
    libraryId: "sys-k8s-shell",
    sectionKey: "terminal.quickCommandLibrary.sections.systemAdministrator",
    subsectionKey: "terminal.quickCommandLibrary.subsections.k8s",
    labelKey: "terminal.quickCommandLibrary.entries.sysK8sShell.label",
    command: "kubectl exec --stdin --tty  -- /bin/sh",
    descriptionKey: "terminal.quickCommandLibrary.entries.sysK8sShell.description",
    iconName: "Terminal",
    accentName: "indigo",
    sendEnter: false,
    confirm: false,
  },
];
